# Generated by Django 2.2.6 on 2020-05-09 08:34

import core.functions
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to=core.functions.file_path_and_rename)),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2020, 5, 9, 13, 34, 15, 812653), verbose_name='Expiration date')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('', 'Select a permission'), ('view', 'Show file'), ('view-write', 'Show file and write comment')], max_length=255, verbose_name='Permission type')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shared_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shared_file_name', related_query_name='user_shared_file', to='content.SharedFile')),
            ],
        ),
    ]
