version: '3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 1337:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./app
    command: celery -A app worker -l info
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - redis
  celery-beat:
    build: ./app
    command: celery -A app beat -l info
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - redis