version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:alpine
  celery:
    build: ./app
    command: celery -A app worker -l info
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - redis
  celery-beat:
    build: ./app
    command: celery -A app beat -l info
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - redis
volumes:
  postgres_data:
  static_volume:
  media_volume: